# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\route.ui'
#
# Created: Wed Mar 30 16:15:38 2016
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DialogRoute(object):
    def setupUi(self, DialogRoute):
        DialogRoute.setObjectName(_fromUtf8("DialogRoute"))
        DialogRoute.setWindowModality(QtCore.Qt.NonModal)
        DialogRoute.resize(270, 449)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/route.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DialogRoute.setWindowIcon(icon)
        DialogRoute.setSizeGripEnabled(True)
        DialogRoute.setModal(False)
        self.gridLayout_2 = QtGui.QGridLayout(DialogRoute)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.formLayout_3 = QtGui.QFormLayout()
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.label_2 = QtGui.QLabel(DialogRoute)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_2)
        self.mMapLayerComboBoxRoad = QgsMapLayerComboBox(DialogRoute)
        self.mMapLayerComboBoxRoad.setObjectName(_fromUtf8("mMapLayerComboBoxRoad"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.mMapLayerComboBoxRoad)
        self.label_5 = QtGui.QLabel(DialogRoute)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_5)
        self.doubleSpinBox = QtGui.QDoubleSpinBox(DialogRoute)
        self.doubleSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox.setDecimals(3)
        self.doubleSpinBox.setMaximum(100000.0)
        self.doubleSpinBox.setObjectName(_fromUtf8("doubleSpinBox"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.doubleSpinBox)
        self.label_7 = QtGui.QLabel(DialogRoute)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_7)
        self.mMapLayerComboBoxCalculatedRoute = QgsMapLayerComboBox(DialogRoute)
        self.mMapLayerComboBoxCalculatedRoute.setObjectName(_fromUtf8("mMapLayerComboBoxCalculatedRoute"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.FieldRole, self.mMapLayerComboBoxCalculatedRoute)
        self.label_8 = QtGui.QLabel(DialogRoute)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_8)
        self.mMapLayerComboBoxManyLongPath = QgsMapLayerComboBox(DialogRoute)
        self.mMapLayerComboBoxManyLongPath.setObjectName(_fromUtf8("mMapLayerComboBoxManyLongPath"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.FieldRole, self.mMapLayerComboBoxManyLongPath)
        self.gridLayout_2.addLayout(self.formLayout_3, 2, 0, 1, 1)
        self.progressBar = QtGui.QProgressBar(DialogRoute)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.gridLayout_2.addWidget(self.progressBar, 4, 0, 1, 1)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.pushButtonStop = QtGui.QPushButton(DialogRoute)
        self.pushButtonStop.setEnabled(False)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/stop.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonStop.setIcon(icon1)
        self.pushButtonStop.setObjectName(_fromUtf8("pushButtonStop"))
        self.gridLayout.addWidget(self.pushButtonStop, 0, 1, 1, 1)
        self.pushButtonStart = QtGui.QPushButton(DialogRoute)
        self.pushButtonStart.setEnabled(False)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/start.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonStart.setIcon(icon2)
        self.pushButtonStart.setObjectName(_fromUtf8("pushButtonStart"))
        self.gridLayout.addWidget(self.pushButtonStart, 0, 0, 1, 1)
        self.pushButtonExit = QtGui.QPushButton(DialogRoute)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/exit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonExit.setIcon(icon3)
        self.pushButtonExit.setObjectName(_fromUtf8("pushButtonExit"))
        self.gridLayout.addWidget(self.pushButtonExit, 0, 2, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 3, 0, 1, 1)
        self.groupBoxSource = QtGui.QGroupBox(DialogRoute)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupBoxSource.setFont(font)
        self.groupBoxSource.setObjectName(_fromUtf8("groupBoxSource"))
        self.gridLayout_8 = QtGui.QGridLayout(self.groupBoxSource)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.checkBoxSelectedSoucePoints = QtGui.QCheckBox(self.groupBoxSource)
        self.checkBoxSelectedSoucePoints.setEnabled(False)
        self.checkBoxSelectedSoucePoints.setChecked(False)
        self.checkBoxSelectedSoucePoints.setObjectName(_fromUtf8("checkBoxSelectedSoucePoints"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.checkBoxSelectedSoucePoints)
        self.label = QtGui.QLabel(self.groupBoxSource)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label)
        self.mMapLayerComboBoxSourcePoints = QgsMapLayerComboBox(self.groupBoxSource)
        self.mMapLayerComboBoxSourcePoints.setObjectName(_fromUtf8("mMapLayerComboBoxSourcePoints"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.mMapLayerComboBoxSourcePoints)
        self.label_9 = QtGui.QLabel(self.groupBoxSource)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_9)
        self.mFieldComboBoxSourcePointsId = QgsFieldComboBox(self.groupBoxSource)
        self.mFieldComboBoxSourcePointsId.setObjectName(_fromUtf8("mFieldComboBoxSourcePointsId"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.mFieldComboBoxSourcePointsId)
        self.label_10 = QtGui.QLabel(self.groupBoxSource)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_10)
        self.mFieldComboBoxSourcePointsName = QgsFieldComboBox(self.groupBoxSource)
        self.mFieldComboBoxSourcePointsName.setObjectName(_fromUtf8("mFieldComboBoxSourcePointsName"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.mFieldComboBoxSourcePointsName)
        self.gridLayout_8.addLayout(self.formLayout, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBoxSource, 0, 0, 1, 1)
        self.groupBoxTarget = QtGui.QGroupBox(DialogRoute)
        self.groupBoxTarget.setObjectName(_fromUtf8("groupBoxTarget"))
        self.gridLayout_10 = QtGui.QGridLayout(self.groupBoxTarget)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.checkBoxSelectedTargetPoints = QtGui.QCheckBox(self.groupBoxTarget)
        self.checkBoxSelectedTargetPoints.setEnabled(False)
        self.checkBoxSelectedTargetPoints.setChecked(False)
        self.checkBoxSelectedTargetPoints.setObjectName(_fromUtf8("checkBoxSelectedTargetPoints"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.checkBoxSelectedTargetPoints)
        self.label_3 = QtGui.QLabel(self.groupBoxTarget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_3)
        self.mMapLayerComboBoxTargetPoints = QgsMapLayerComboBox(self.groupBoxTarget)
        self.mMapLayerComboBoxTargetPoints.setObjectName(_fromUtf8("mMapLayerComboBoxTargetPoints"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.mMapLayerComboBoxTargetPoints)
        self.label_11 = QtGui.QLabel(self.groupBoxTarget)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_11)
        self.mFieldComboBoxTargetPointsId = QgsFieldComboBox(self.groupBoxTarget)
        self.mFieldComboBoxTargetPointsId.setObjectName(_fromUtf8("mFieldComboBoxTargetPointsId"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.mFieldComboBoxTargetPointsId)
        self.label_12 = QtGui.QLabel(self.groupBoxTarget)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_12)
        self.mFieldComboBoxTargetPointsName = QgsFieldComboBox(self.groupBoxTarget)
        self.mFieldComboBoxTargetPointsName.setObjectName(_fromUtf8("mFieldComboBoxTargetPointsName"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.mFieldComboBoxTargetPointsName)
        self.gridLayout_10.addLayout(self.formLayout_2, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBoxTarget, 1, 0, 1, 1)

        self.retranslateUi(DialogRoute)
        QtCore.QObject.connect(self.mMapLayerComboBoxSourcePoints, QtCore.SIGNAL(_fromUtf8("layerChanged(QgsMapLayer*)")), self.mFieldComboBoxSourcePointsId.setLayer)
        QtCore.QObject.connect(self.mMapLayerComboBoxTargetPoints, QtCore.SIGNAL(_fromUtf8("layerChanged(QgsMapLayer*)")), self.mFieldComboBoxTargetPointsId.setLayer)
        QtCore.QObject.connect(self.mMapLayerComboBoxSourcePoints, QtCore.SIGNAL(_fromUtf8("layerChanged(QgsMapLayer*)")), self.mFieldComboBoxSourcePointsName.setLayer)
        QtCore.QObject.connect(self.mMapLayerComboBoxTargetPoints, QtCore.SIGNAL(_fromUtf8("layerChanged(QgsMapLayer*)")), self.mFieldComboBoxTargetPointsName.setLayer)
        QtCore.QMetaObject.connectSlotsByName(DialogRoute)
        DialogRoute.setTabOrder(self.checkBoxSelectedSoucePoints, self.mMapLayerComboBoxSourcePoints)
        DialogRoute.setTabOrder(self.mMapLayerComboBoxSourcePoints, self.mFieldComboBoxSourcePointsId)
        DialogRoute.setTabOrder(self.mFieldComboBoxSourcePointsId, self.mFieldComboBoxSourcePointsName)
        DialogRoute.setTabOrder(self.mFieldComboBoxSourcePointsName, self.checkBoxSelectedTargetPoints)
        DialogRoute.setTabOrder(self.checkBoxSelectedTargetPoints, self.mMapLayerComboBoxTargetPoints)
        DialogRoute.setTabOrder(self.mMapLayerComboBoxTargetPoints, self.mFieldComboBoxTargetPointsId)
        DialogRoute.setTabOrder(self.mFieldComboBoxTargetPointsId, self.mFieldComboBoxTargetPointsName)
        DialogRoute.setTabOrder(self.mFieldComboBoxTargetPointsName, self.mMapLayerComboBoxRoad)
        DialogRoute.setTabOrder(self.mMapLayerComboBoxRoad, self.doubleSpinBox)
        DialogRoute.setTabOrder(self.doubleSpinBox, self.mMapLayerComboBoxCalculatedRoute)
        DialogRoute.setTabOrder(self.mMapLayerComboBoxCalculatedRoute, self.mMapLayerComboBoxManyLongPath)
        DialogRoute.setTabOrder(self.mMapLayerComboBoxManyLongPath, self.pushButtonStart)
        DialogRoute.setTabOrder(self.pushButtonStart, self.pushButtonStop)
        DialogRoute.setTabOrder(self.pushButtonStop, self.pushButtonExit)

    def retranslateUi(self, DialogRoute):
        DialogRoute.setWindowTitle(_translate("DialogRoute", "Routes calculation", None))
        self.label_2.setText(_translate("DialogRoute", "Map layer road network", None))
        self.label_5.setText(_translate("DialogRoute", "Maximum route length (kilometers)", None))
        self.label_7.setText(_translate("DialogRoute", "Map layer for calculated routes", None))
        self.label_8.setText(_translate("DialogRoute", "Table routes, longer maximum", None))
        self.pushButtonStop.setText(_translate("DialogRoute", "Stop", None))
        self.pushButtonStart.setText(_translate("DialogRoute", "Run", None))
        self.pushButtonExit.setText(_translate("DialogRoute", "Close", None))
        self.groupBoxSource.setTitle(_translate("DialogRoute", "Layer source (from points)", None))
        self.checkBoxSelectedSoucePoints.setText(_translate("DialogRoute", "Only selected points", None))
        self.label.setText(_translate("DialogRoute", "Map layer source", None))
        self.label_9.setText(_translate("DialogRoute", "ID field", None))
        self.label_10.setText(_translate("DialogRoute", "Name field", None))
        self.groupBoxTarget.setTitle(_translate("DialogRoute", "Layer target (to points)", None))
        self.checkBoxSelectedTargetPoints.setText(_translate("DialogRoute", "Only selected points", None))
        self.label_3.setText(_translate("DialogRoute", "Map layer target", None))
        self.label_11.setText(_translate("DialogRoute", "ID field", None))
        self.label_12.setText(_translate("DialogRoute", "Name field", None))

from qgsfieldcombobox import QgsFieldComboBox
from qgsmaplayercombobox import QgsMapLayerComboBox
import resources_rc
